/**
 * Fetches the KenPom ratings table and generates lib/kenpom-data.ts.
 *
 * Usage:
 *   npx tsx scripts/fetch-kenpom.ts              # try web, fall back to local file
 *   npx tsx scripts/fetch-kenpom.ts --file kenpom.html  # parse saved HTML file
 *
 * To update data: visit https://kenpom.com/, save the page as HTML,
 * then run: npx tsx scripts/fetch-kenpom.ts --file saved-page.html
 */

import * as cheerio from "cheerio";
import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

interface KenpomRating {
  rank: number;
  team: string;
  conference: string;
  wins: number;
  losses: number;
  adjEM: number;
  adjO: number;
  adjORank: number;
  adjD: number;
  adjDRank: number;
  adjTempo: number;
  adjTempoRank: number;
  luck: number;
  luckRank: number;
  sosEM: number;
  sosEMRank: number;
  ncsosEM: number;
  ncsosEMRank: number;
}

function parseNum(text: string): number {
  const cleaned = text.replace(/[+\s]/g, "").trim();
  const num = parseFloat(cleaned);
  return isNaN(num) ? 0 : num;
}

function parseInt2(text: string): number {
  const num = parseInt(text.trim(), 10);
  return isNaN(num) ? 0 : num;
}

function parseHtml(html: string): KenpomRating[] {
  const $ = cheerio.load(html);
  const ratings: KenpomRating[] = [];

  $("#ratings-table tbody tr").each((_i, row) => {
    const cells = $(row).find("td");
    if (cells.length < 21) return;

    const rank = parseInt2($(cells[0]).text());
    if (rank === 0) return;

    let teamName = $(cells[1]).find("a").first().text().trim() || $(cells[1]).text().trim();
    teamName = teamName.replace(/\s+\d+$/, "").trim();

    const conference = $(cells[2]).find("a").first().text().trim() || $(cells[2]).text().trim();
    const recordParts = $(cells[3]).text().trim().split("-");
    const wins = parseInt2(recordParts[0] ?? "0");
    const losses = parseInt2(recordParts[1] ?? "0");

    ratings.push({
      rank,
      team: teamName,
      conference,
      wins,
      losses,
      adjEM: parseNum($(cells[4]).text()),
      adjO: parseNum($(cells[5]).text()),
      adjORank: parseInt2($(cells[6]).text()),
      adjD: parseNum($(cells[7]).text()),
      adjDRank: parseInt2($(cells[8]).text()),
      adjTempo: parseNum($(cells[9]).text()),
      adjTempoRank: parseInt2($(cells[10]).text()),
      luck: parseNum($(cells[11]).text()),
      luckRank: parseInt2($(cells[12]).text()),
      sosEM: parseNum($(cells[13]).text()),
      sosEMRank: parseInt2($(cells[14]).text()),
      ncsosEM: parseNum($(cells[19]).text()),
      ncsosEMRank: parseInt2($(cells[20]).text()),
    });
  });

  return ratings;
}

async function fetchFromWeb(): Promise<string | null> {
  try {
    console.log("Trying to fetch from https://kenpom.com/ ...");
    const response = await fetch("https://kenpom.com/", {
      headers: {
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
        Accept: "text/html,application/xhtml+xml",
      },
    });
    if (!response.ok) {
      console.log(`Web fetch returned ${response.status}, falling back to local file.`);
      return null;
    }
    return await response.text();
  } catch (e) {
    console.log(`Web fetch failed: ${e}, falling back to local file.`);
    return null;
  }
}

function generateTypeScriptFile(ratings: KenpomRating[]): string {
  const date = new Date().toISOString().split("T")[0];

  let out = `// Auto-generated by scripts/fetch-kenpom.ts on ${date}\n`;
  out += `// Source: https://kenpom.com/\n\n`;

  out += `export interface KenpomRating {\n`;
  out += `  rank: number;\n`;
  out += `  team: string;\n`;
  out += `  conference: string;\n`;
  out += `  wins: number;\n`;
  out += `  losses: number;\n`;
  out += `  /** Adjusted Efficiency Margin (points per 100 possessions above average) */\n`;
  out += `  adjEM: number;\n`;
  out += `  /** Adjusted Offensive Efficiency */\n`;
  out += `  adjO: number;\n`;
  out += `  adjORank: number;\n`;
  out += `  /** Adjusted Defensive Efficiency (lower = better) */\n`;
  out += `  adjD: number;\n`;
  out += `  adjDRank: number;\n`;
  out += `  /** Adjusted Tempo (possessions per game) */\n`;
  out += `  adjTempo: number;\n`;
  out += `  adjTempoRank: number;\n`;
  out += `  /** Luck rating */\n`;
  out += `  luck: number;\n`;
  out += `  luckRank: number;\n`;
  out += `  /** Strength of Schedule (efficiency margin) */\n`;
  out += `  sosEM: number;\n`;
  out += `  sosEMRank: number;\n`;
  out += `  /** Non-Conference Strength of Schedule */\n`;
  out += `  ncsosEM: number;\n`;
  out += `  ncsosEMRank: number;\n`;
  out += `}\n\n`;

  out += `/** KenPom ratings keyed by team name (${ratings.length} teams) */\n`;
  out += `export const KENPOM_RATINGS: Record<string, KenpomRating> = {\n`;

  for (const r of ratings) {
    const key = JSON.stringify(r.team);
    out += `  ${key}: { rank: ${r.rank}, team: ${key}, conference: "${r.conference}", wins: ${r.wins}, losses: ${r.losses}, adjEM: ${r.adjEM}, adjO: ${r.adjO}, adjORank: ${r.adjORank}, adjD: ${r.adjD}, adjDRank: ${r.adjDRank}, adjTempo: ${r.adjTempo}, adjTempoRank: ${r.adjTempoRank}, luck: ${r.luck}, luckRank: ${r.luckRank}, sosEM: ${r.sosEM}, sosEMRank: ${r.sosEMRank}, ncsosEM: ${r.ncsosEM}, ncsosEMRank: ${r.ncsosEMRank} },\n`;
  }

  out += `};\n`;
  return out;
}

async function main() {
  const args = process.argv.slice(2);
  const fileIdx = args.indexOf("--file");
  let html: string | null = null;

  if (fileIdx !== -1 && args[fileIdx + 1]) {
    const filePath = args[fileIdx + 1];
    console.log(`Reading from local file: ${filePath}`);
    html = readFileSync(filePath, "utf-8");
  } else {
    html = await fetchFromWeb();
  }

  if (!html) {
    console.log("\nTo update KenPom data:");
    console.log("  1. Visit https://kenpom.com/ in your browser");
    console.log("  2. Save the page as HTML (Cmd+S / Ctrl+S)");
    console.log("  3. Run: npx tsx scripts/fetch-kenpom.ts --file path/to/saved.html");
    process.exit(1);
  }

  const ratings = parseHtml(html);
  if (ratings.length === 0) {
    console.error("No ratings parsed! The HTML structure may have changed.");
    process.exit(1);
  }

  console.log(`Parsed ${ratings.length} teams.`);
  for (const r of ratings.slice(0, 5)) {
    console.log(`  #${r.rank} ${r.team} (${r.conference}) ${r.wins}-${r.losses} | AdjEM: ${r.adjEM > 0 ? "+" : ""}${r.adjEM}`);
  }

  const tsContent = generateTypeScriptFile(ratings);
  const outputPath = join(import.meta.dirname!, "..", "lib", "kenpom-data.ts");
  writeFileSync(outputPath, tsContent, "utf-8");
  console.log(`\nWritten to ${outputPath}`);
}

main();
